FROM nginx:alpine

# 删除默认 server 配置
RUN rm /etc/nginx/conf.d/default.conf

# 拷贝你自己的 server 配置
COPY nginx.conf /etc/nginx/conf.d/default.conf

# 拷贝静态文件
COPY static/ /usr/share/nginx/html/

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]